### ISSUE TITLE
Contrast in alerts

### ISSUE THREAD

**Issue by JackuB** [apiaryio/base-styles#5]
@tjerabek we need to workout how to handle links in alerts, because in current form we have issues with contrast:

<img width="733" alt="snimek obrazovky 2017-01-12 v 13 04 13" src="https://cloud.githubusercontent.com/assets/1788727/21889178/e8113cf0-d8c7-11e6-84f7-5509443623b2.png">

We can make the background lighter:

<img width="722" alt="snimek obrazovky 2017-01-12 v 13 04 17" src="https://cloud.githubusercontent.com/assets/1788727/21889181/f06297f0-d8c7-11e6-9c47-aaf531924322.png">

Thoughts?

**Comment by tjerabek** [comment]
@JackuB I think lighter background color could work!
